server:
  port: 8028
spring:
  application:
    name: swag-profile
  data:
    mongodb:
      uri: mongodb+srv://JuancaJcA:5iNlK1vFPU6KWwpq@labooncluster.ptkenzc.mongodb.net/?retryWrites=true&w=majority
      database: Software
  zipkin:
    base-url: http://localhost:9411/
    locator:
      discovery:
        enabled: true
  rabbitmq:
    host: sparrow-01.rmq.cloudamqp.com
    port: 5672
    username: jwotlglz
    password: jKyraqfBLVG1hW9RRm1P63au9sJJ-uNd
    virtual-host: jwotlglz

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
#      defaultZone: http://swag-discovery:8703/eureka/
      defaultZone: http://localhost:8703/eureka/
    enabled: true
